[project]
name = "upstage-documentparse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dify-plugin>=0.0.1b73",
    "jupyter>=1.1.1",
    "notebook>=7.3.2",
]
